version: '3.8'

services:
    portfolio: 
        container_name: portfolio-app
        image: portfolio-app
        build:
            context: . 
            target: development
        volumes:
            - ./src:/app/src
        ports:
            - 3000:3000
